# format_doc_comments = true
# imports_layout = "Vertical"
# match_block_trailing_comma = true
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# report_fixme = "Unnumbered"
# report_todo = "Unnumbered"
# spaces_around_ranges = true
# struct_field_align_threshold = 20
# wrap_comments = true
hard_tabs = true
use_field_init_shorthand = true