[package]
edition = "2018"
license = "MIT"
name = "tangram_util"
version = "0.1.0-dev"

[lib]
path = "lib.rs"

[dev-dependencies]
rayon = "1.4"

[dependencies]
backtrace = "0.3"
num-traits = "0.2"
rand = "0.7"
serde = "1"
