[package]
edition = "2018"
license = "MIT"
name = "tangram_util"
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
crossbeam = "0.7"
num-traits = "0.2"
once_cell = "1"
rand = "0.7"
rayon = "1.4"
serde = "1"
