[package]
edition = "2018"
name = "tangram_www"
version = "0.0.0"

[[bin]]
name = "tangram_www"
path = "main.rs"

[dependencies]
tangram_deps = { path = "../deps" }
tangram_util = { path = "../util" }
