[package]
edition = "2018"
name = "tangram_www"
version = "0.0.0"

[[bin]]
name = "www"
path = "main.rs"

[dependencies]
tangram_ui = { path = "../ui" }
tangram_util = { path = "../util" }
tangram_www_pages_index = { path = "pages/index" }
