# This is an example config file for the heart disease dataset.
columns: # Specify the subset of columns to train with, excluding the target column. This feature is not yet implemented.
  - name: age
  - name: gender
  - name: chest_pain
  - name: resting_blood_pressure
  - name: cholesterol
  - name: fasting_blood_sugar_greater_than_120
  - name: resting_ecg_result
  - name: exercise_max_heart_rate
  - name: exercise_induced_angina
  - name: exercise_st_depression
  - name: exercise_st_slope
  - name: fluoroscopy_vessels_colored
  - name: thallium_stress_test
task: classification # The task can be either regression or classification. If omitted, the task is inferred from the type of the target column: regression for `Number` columns and classification for `Enum` columns.
model_comparison_metric: auc # Specify the metric with which to choose the best model. The options are, for regression: `rmse`, for binary classification: `accuracy`, `auc`, or `f1score`, for multiclass classification: `accuracy`.
train_test_split:
  train: 0.8 # The percent of the dataset that will be used to train each model.
  # validation: 0.1 # The percent of the dataset that will be held out to choose the best model.
  test: 0.2 # The percent of the dataset that will be held out to evaluate the final model chosen.
grid:
  - model: tree
    learning_rate: 0.1
    depth: 3 # Each tree will have at most 2^depth nodes.
    max_trees: 100 # The maximum number of trees to train.
    min_examples_per_branch: 2 # The minimum number of examples required to continue splitting
    min_examples_per_leaf: 1 # The minimum number of examples required for a leaf node
  - model: linear
    learning_rate: 0.1
    l2_regularization: 0.1
    max_epochs: 100 # The maximum number of epochs to train for.
    n_examples_per_batch: 128 # The number of examples in each minibatch of training.
