[package]
name = "html-macro"
version = "0.0.0"
edition = "2018"
license = "MIT"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
