[package]
name = "tangram-rust"
version = "0.1.3"
authors = ["Tangram root@tangramhq.com"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
libc = "0.2"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
