import * as ui from '@tangramhq/ui'
import { h } from 'preact'

export function Training() {
	return <ui.Asciicast asciicast={asciicast} height="380px" repeat={false} />
}

let asciicast: ui.AsciicastEvent[] = [
	[0.0, `<span style="color: ${'var(--red)'}; font-weight: bold">$</span> `],
	[0.231235, 't'],
	[0.344881, 'a'],
	[0.478167, 'n'],
	[0.826294, 'g'],
	[0.860464, 'r'],
	[0.972665, 'a'],
	[1.108968, 'm'],
	[1.355563, ' '],
	[1.478951, 't'],
	[1.557548, 'r'],
	[1.613993, 'a'],
	[1.659268, 'i'],
	[1.727182, 'n'],
	[1.829055, ' '],
	[1.929642, '-'],
	[2.044044, '-'],
	[2.109304, 'f'],
	[2.224933, 'i'],
	[2.312332, 'l'],
	[2.36884, 'e'],
	[2.469032, ' '],
	[2.548294, 'h'],
	[2.626485, 'e'],
	[2.752146, 'a'],
	[2.965486, 'r'],
	[3.100431, 't'],
	[3.201051, '-'],
	[3.324643, 'd'],
	[3.41524, 'i'],
	[3.573692, 's'],
	[3.719609, 'e'],
	[3.843145, 'a'],
	[3.977601, 's'],
	[4.091148, 'e'],
	[4.213607, '.'],
	[4.327146, 'c'],
	[4.394568, 's'],
	[4.505512, 'v'],
	[4.709437, ' '],
	[4.889475, '-'],
	[5.024445, '-'],
	[5.114513, 't'],
	[5.226863, 'a'],
	[5.317003, 'r'],
	[5.496553, 'g'],
	[5.609646, 'e'],
	[5.766834, 't'],
	[5.981275, ' '],
	[6.115701, 'd'],
	[6.206282, 'i'],
	[6.261761, 'a'],
	[6.498363, 'g'],
	[6.588725, 'n'],
	[6.758256, 'o'],
	[6.869651, 's'],
	[6.889651, 'i'],
	[6.914535, 's'],
	[7.0, '<br>'],
	[
		7.5,
		'##&nbsp;Overview<br><br>You&nbsp;trained&nbsp;a&nbsp;linear&nbsp;binary&nbsp;classifier&nbsp;to&nbsp;predict&nbsp;the&nbsp;column&nbsp;"diagnosis".<br><br>|---------------|--------------------------|<br>|&nbsp;Model&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;linear&nbsp;binary&nbsp;classifier&nbsp;|<br>|---------------|--------------------------|<br>|&nbsp;Target&nbsp;Column&nbsp;|&nbsp;diagnosis&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|---------------|--------------------------|<br><br>##&nbsp;🎯&nbsp;Target&nbsp;Column<br><br>|-----------|------|<br>|&nbsp;Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Type&nbsp;|<br>|-----------|------|<br>|&nbsp;diagnosis&nbsp;|&nbsp;Enum&nbsp;|<br>|-----------|------|<br>|---------------|<br>|&nbsp;Unique&nbsp;Values&nbsp;|<br>|---------------|<br>|&nbsp;Negative&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;Positive&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|---------------|<br><br>##&nbsp;Columns<br><br>Your&nbsp;dataset&nbsp;has&nbsp;13&nbsp;columns&nbsp;excluding&nbsp;the&nbsp;target&nbsp;column<br><br>|--------------------------------------|--------|<br>|&nbsp;Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Type&nbsp;&nbsp;&nbsp;|<br>|--------------------------------------|--------|<br>|&nbsp;age&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Number&nbsp;|<br>|&nbsp;gender&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;chest_pain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;resting_blood_pressure&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Number&nbsp;|<br>|&nbsp;cholesterol&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Number&nbsp;|<br>|&nbsp;fasting_blood_sugar_greater_than_120&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;resting_ecg_result&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;exercise_max_heart_rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Number&nbsp;|<br>|&nbsp;exercise_induced_angina&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;exercise_st_depression&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Number&nbsp;|<br>|&nbsp;exercise_st_slope&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;fluoroscopy_vessels_colored&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|&nbsp;thallium_stress_test&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Enum&nbsp;&nbsp;&nbsp;|<br>|--------------------------------------|--------|<br><br>##&nbsp;Metrics<br><br>The&nbsp;baseline&nbsp;accuracy&nbsp;is&nbsp;the&nbsp;accuracy&nbsp;that&nbsp;a&nbsp;model&nbsp;would&nbsp;get&nbsp;if&nbsp;it&nbsp;always&nbsp;predicted&nbsp;the&nbsp;majority&nbsp;class.<br><br>|-------------------|-----------|<br>|&nbsp;Accuracy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;0.8360656&nbsp;|<br>|&nbsp;Baseline&nbsp;Accuracy&nbsp;|&nbsp;0.6393443&nbsp;|<br>|-------------------|-----------|<br><br>Your&nbsp;model&nbsp;was&nbsp;written&nbsp;to&nbsp;/Users/nitsky/code/tangram/heart-disease.tangram.<br>For&nbsp;help&nbsp;making&nbsp;predictions&nbsp;from&nbsp;your&nbsp;code,&nbsp;check&nbsp;out&nbsp;https://www.tangramhq.com/docs/predict.<br>',
	],
]
