[package]
name = "include_out_dir_macro"
version = "0.0.0"
edition = "2018"
license = "MIT"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
walkdir = "2"
